<?php

// Validated by Gerti
/*
 {
         "component":"HmIP-SWO-PR",
         "parent_device_type":"HmIP-SWO-PR",
         "parent_device_interface":"HmIP-RF",
         "name":"Wetterstation:0",
         "type":"30",
         "address":"00185F299965B4:0",
         "ise_id":"39233",
         "direction":"UNKNOWN",
         "parent_device":"39232",
         "index":"0",
         "group_partner":"",
         "aes_available":"false",
         "transmission_mode":"AES",
         "visible":"true",
         "ready_config":"true",
         "operate":"true",
         "datapoints":[
            {
               "name":"HmIP-RF.00185F299965B4:0.CONFIG_PENDING",
               "type":"CONFIG_PENDING",
               "ise_id":"39234",
               "state":"false",
               "value":"false",
               "valuetype":"2",
               "valueunit":"",
               "timestamp":"1690128607",
               "operations":"5"
            },
            {
               "name":"HmIP-RF.00185F299965B4:0.DUTY_CYCLE",
               "type":"DUTY_CYCLE",
               "ise_id":"39238",
               "state":"false",
               "value":"false",
               "valuetype":"2",
               "valueunit":"",
               "timestamp":"1690128607",
               "operations":"5"
            },
            {
               "name":"HmIP-RF.00185F299965B4:0.ERROR_CODE",
               "type":"ERROR_CODE",
               "ise_id":"39239",
               "state":"0",
               "value":"0",
               "valuetype":"16",
               "valueunit":"",
               "timestamp":"1690128607",
               "operations":"5"
            },
            {
               "name":"HmIP-RF.00185F299965B4:0.ERROR_WIND_COMMUNICATION",
               "type":"ERROR_WIND_COMMUNICATION",
               "ise_id":"39240",
               "state":"false",
               "value":"false",
               "valuetype":"2",
               "valueunit":"",
               "timestamp":"1690128607",
               "operations":"5"
            },
            {
               "name":"HmIP-RF.00185F299965B4:0.ERROR_WIND_NORTH",
               "type":"ERROR_WIND_NORTH",
               "ise_id":"39241",
               "state":"false",
               "value":"false",
               "valuetype":"2",
               "valueunit":"",
               "timestamp":"1690128607",
               "operations":"5"
            },
            {
               "name":"HmIP-RF.00185F299965B4:0.LOW_BAT",
               "type":"LOW_BAT",
               "ise_id":"39243",
               "state":"false",
               "value":"false",
               "valuetype":"2",
               "valueunit":"",
               "timestamp":"1690128607",
               "operations":"5"
            },
            {
               "name":"HmIP-RF.00185F299965B4:0.RSSI_DEVICE",
               "type":"RSSI_DEVICE",
               "ise_id":"39247",
               "state":"-84",
               "value":"-84",
               "valuetype":"16",
               "valueunit":"",
               "timestamp":"1690128607",
               "operations":"5"
            },
            {
               "name":"HmIP-RF.00185F299965B4:0.RSSI_PEER",
               "type":"RSSI_PEER",
               "ise_id":"39248",
               "state":"0",
               "value":"0",
               "valuetype":"16",
               "valueunit":"",
               "timestamp":"0",
               "operations":"5"
            },
            {
               "name":"HmIP-RF.00185F299965B4:0.TEMPERATURE_OUT_OF_RANGE",
               "type":"TEMPERATURE_OUT_OF_RANGE",
               "ise_id":"39249",
               "state":"false",
               "value":"false",
               "valuetype":"2",
               "valueunit":"",
               "timestamp":"1690128607",
               "operations":"5"
            },
            {
               "name":"HmIP-RF.00185F299965B4:0.UNREACH",
               "type":"UNREACH",
               "ise_id":"39250",
               "state":"false",
               "value":"false",
               "valuetype":"2",
               "valueunit":"",
               "timestamp":"1690128607",
               "operations":"5"
            },
            {
               "name":"HmIP-RF.00185F299965B4:0.UPDATE_PENDING",
               "type":"UPDATE_PENDING",
               "ise_id":"39254",
               "state":"false",
               "value":"false",
               "valuetype":"2",
               "valueunit":"",
               "timestamp":"1690128607",
               "operations":"5"
            }
         ]
      },
      {
         "component":"HmIP-SWO-PR",
         "parent_device_type":"HmIP-SWO-PR",
         "parent_device_interface":"HmIP-RF",
         "name":"Wetterdaten",
         "type":"22",
         "address":"00185F299965B4:1",
         "ise_id":"39258",
         "direction":"UNKNOWN",
         "parent_device":"39232",
         "index":"1",
         "group_partner":"",
         "aes_available":"false",
         "transmission_mode":"AES",
         "visible":"true",
         "ready_config":"true",
         "operate":"true",
         "datapoints":[
            {
               "name":"HmIP-RF.00185F299965B4:1.ACTUAL_TEMPERATURE",
               "type":"ACTUAL_TEMPERATURE",
               "ise_id":"39259",
               "state":"20.100000",
               "value":"20.100000",
               "valuetype":"4",
               "valueunit":"\u00b0C",
               "timestamp":"1690128607",
               "operations":"5"
            },
            {
               "name":"HmIP-RF.00185F299965B4:1.ACTUAL_TEMPERATURE_STATUS",
               "type":"ACTUAL_TEMPERATURE_STATUS",
               "ise_id":"39260",
               "state":"0",
               "value":"0",
               "valuetype":"16",
               "valueunit":"",
               "timestamp":"1690128607",
               "operations":"5"
            },
            {
               "name":"HmIP-RF.00185F299965B4:1.HUMIDITY",
               "type":"HUMIDITY",
               "ise_id":"39261",
               "state":"82",
               "value":"82",
               "valuetype":"16",
               "valueunit":"% rF",
               "timestamp":"1690128607",
               "operations":"5"
            },
            {
               "name":"HmIP-RF.00185F299965B4:1.HUMIDITY_STATUS",
               "type":"HUMIDITY_STATUS",
               "ise_id":"39262",
               "state":"0",
               "value":"0",
               "valuetype":"16",
               "valueunit":"",
               "timestamp":"1690128607",
               "operations":"5"
            },
            {
               "name":"HmIP-RF.00185F299965B4:1.ILLUMINATION",
               "type":"ILLUMINATION",
               "ise_id":"39263",
               "state":"4151.000000",
               "value":"4151.000000",
               "valuetype":"4",
               "valueunit":"",
               "timestamp":"1690128607",
               "operations":"5"
            },
            {
               "name":"HmIP-RF.00185F299965B4:1.ILLUMINATION_STATUS",
               "type":"ILLUMINATION_STATUS",
               "ise_id":"39264",
               "state":"0",
               "value":"0",
               "valuetype":"16",
               "valueunit":"",
               "timestamp":"1690128607",
               "operations":"5"
            },
            {
               "name":"HmIP-RF.00185F299965B4:1.RAINING",
               "type":"RAINING",
               "ise_id":"39265",
               "state":"false",
               "value":"false",
               "valuetype":"2",
               "valueunit":"",
               "timestamp":"1690128607",
               "operations":"5"
            },
            {
               "name":"HmIP-RF.00185F299965B4:1.RAIN_COUNTER",
               "type":"RAIN_COUNTER",
               "ise_id":"39266",
               "state":"54.600000",
               "value":"54.600000",
               "valuetype":"4",
               "valueunit":"mm",
               "timestamp":"1690128607",
               "operations":"5"
            },
            {
               "name":"HmIP-RF.00185F299965B4:1.RAIN_COUNTER_OVERFLOW",
               "type":"RAIN_COUNTER_OVERFLOW",
               "ise_id":"39267",
               "state":"false",
               "value":"false",
               "valuetype":"2",
               "valueunit":"",
               "timestamp":"1690128607",
               "operations":"5"
            },
            {
               "name":"HmIP-RF.00185F299965B4:1.RAIN_COUNTER_STATUS",
               "type":"RAIN_COUNTER_STATUS",
               "ise_id":"39268",
               "state":"0",
               "value":"0",
               "valuetype":"16",
               "valueunit":"",
               "timestamp":"1690128607",
               "operations":"5"
            },
            {
               "name":"HmIP-RF.00185F299965B4:1.SUNSHINEDURATION",
               "type":"SUNSHINEDURATION",
               "ise_id":"39269",
               "state":"2118",
               "value":"2118",
               "valuetype":"16",
               "valueunit":"min",
               "timestamp":"1690128607",
               "operations":"5"
            },
            {
               "name":"HmIP-RF.00185F299965B4:1.SUNSHINEDURATION_OVERFLOW",
               "type":"SUNSHINEDURATION_OVERFLOW",
               "ise_id":"39270",
               "state":"true",
               "value":"true",
               "valuetype":"2",
               "valueunit":"",
               "timestamp":"1690128607",
               "operations":"5"
            },
            {
               "name":"HmIP-RF.00185F299965B4:1.SUNSHINE_THRESHOLD_OVERRUN",
               "type":"SUNSHINE_THRESHOLD_OVERRUN",
               "ise_id":"39271",
               "state":"true",
               "value":"true",
               "valuetype":"2",
               "valueunit":"",
               "timestamp":"1690128607",
               "operations":"5"
            },
            {
               "name":"HmIP-RF.00185F299965B4:1.WIND_DIR",
               "type":"WIND_DIR",
               "ise_id":"39272",
               "state":"192.500000",
               "value":"192.500000",
               "valuetype":"4",
               "valueunit":"\u00b0",
               "timestamp":"1690128607",
               "operations":"5"
            },
            {
               "name":"HmIP-RF.00185F299965B4:1.WIND_DIR_RANGE",
               "type":"WIND_DIR_RANGE",
               "ise_id":"39273",
               "state":"22.500000",
               "value":"22.500000",
               "valuetype":"4",
               "valueunit":"\u00b0",
               "timestamp":"1690128607",
               "operations":"5"
            },
            {
               "name":"HmIP-RF.00185F299965B4:1.WIND_DIR_RANGE_STATUS",
               "type":"WIND_DIR_RANGE_STATUS",
               "ise_id":"39274",
               "state":"0",
               "value":"0",
               "valuetype":"16",
               "valueunit":"",
               "timestamp":"1690128607",
               "operations":"5"
            },
            {
               "name":"HmIP-RF.00185F299965B4:1.WIND_DIR_STATUS",
               "type":"WIND_DIR_STATUS",
               "ise_id":"39275",
               "state":"0",
               "value":"0",
               "valuetype":"16",
               "valueunit":"",
               "timestamp":"1690128607",
               "operations":"5"
            },
            {
               "name":"HmIP-RF.00185F299965B4:1.WIND_SPEED",
               "type":"WIND_SPEED",
               "ise_id":"39276",
               "state":"23.100000",
               "value":"23.100000",
               "valuetype":"4",
               "valueunit":"km\/h",
               "timestamp":"1690128607",
               "operations":"5"
            },
            {
               "name":"HmIP-RF.00185F299965B4:1.WIND_SPEED_STATUS",
               "type":"WIND_SPEED_STATUS",
               "ise_id":"39277",
               "state":"0",
               "value":"0",
               "valuetype":"16",
               "valueunit":"",
               "timestamp":"1690128607",
               "operations":"5"
            },
            {
               "name":"HmIP-RF.00185F299965B4:1.WIND_THRESHOLD_OVERRUN",
               "type":"WIND_THRESHOLD_OVERRUN",
               "ise_id":"39278",
               "state":"true",
               "value":"true",
               "valuetype":"2",
               "valueunit":"",
               "timestamp":"1690128607",
               "operations":"5"
            }
         ]
      },
      {
         "component":"HmIP-SWO-PR",
         "parent_device_type":"HmIP-SWO-PR",
         "parent_device_interface":"HmIP-RF",
         "name":"Windgeschwindigkeit",
         "type":"26",
         "address":"00185F299965B4:2",
         "ise_id":"39279",
         "direction":"SENDER",
         "parent_device":"39232",
         "index":"2",
         "group_partner":"",
         "aes_available":"false",
         "transmission_mode":"AES",
         "visible":"true",
         "ready_config":"true",
         "operate":"true"
      },
      {
         "component":"HmIP-SWO-PR",
         "parent_device_type":"HmIP-SWO-PR",
         "parent_device_interface":"HmIP-RF",
         "name":"HmIP-SWO-PR 00185F299965B4:3",
         "type":"26",
         "address":"00185F299965B4:3",
         "ise_id":"39280",
         "direction":"SENDER",
         "parent_device":"39232",
         "index":"3",
         "group_partner":"",
         "aes_available":"false",
         "transmission_mode":"AES",
         "visible":"true",
         "ready_config":"true",
         "operate":"true"
      },
      {
         "component":"HmIP-SWO-PR",
         "parent_device_type":"HmIP-SWO-PR",
         "parent_device_interface":"HmIP-RF",
         "name":"HmIP-SWO-PR 00185F299965B4:4",
         "type":"26",
         "address":"00185F299965B4:4",
         "ise_id":"39281",
         "direction":"SENDER",
         "parent_device":"39232",
         "index":"4",
         "group_partner":"",
         "aes_available":"false",
         "transmission_mode":"AES",
         "visible":"true",
         "ready_config":"true",
         "operate":"true"
      },
      {
         "component":"HmIP-SWO-PR",
         "parent_device_type":"HmIP-SWO-PR",
         "parent_device_interface":"HmIP-RF",
         "name":"Helligkeit",
         "type":"26",
         "address":"00185F299965B4:5",
         "ise_id":"39282",
         "direction":"SENDER",
         "parent_device":"39232",
         "index":"5",
         "group_partner":"",
         "aes_available":"false",
         "transmission_mode":"AES",
         "visible":"true",
         "ready_config":"true",
         "operate":"true"
      },
      {
         "component":"HmIP-SWO-PR",
         "parent_device_type":"HmIP-SWO-PR",
         "parent_device_interface":"HmIP-RF",
         "name":"Regenmenge",
         "type":"26",
         "address":"00185F299965B4:6",
         "ise_id":"39283",
         "direction":"SENDER",
         "parent_device":"39232",
         "index":"6",
         "group_partner":"",
         "aes_available":"false",
         "transmission_mode":"AES",
         "visible":"true",
         "ready_config":"true",
         "operate":"true"
      },
      {
         "component":"HmIP-SWO-PR",
         "parent_device_type":"HmIP-SWO-PR",
         "parent_device_interface":"HmIP-RF",
         "name":"HmIP-SWO-PR 00185F299965B4:7",
         "type":"26",
         "address":"00185F299965B4:7",
         "ise_id":"39284",
         "direction":"SENDER",
         "parent_device":"39232",
         "index":"7",
         "group_partner":"",
         "aes_available":"false",
         "transmission_mode":"AES",
         "visible":"true",
         "ready_config":"true",
         "operate":"true"
      },
      {
         "component":"HmIP-SWO-PR",
         "parent_device_type":"HmIP-SWO-PR",
         "parent_device_interface":"HmIP-RF",
         "name":"Windrichtung",
         "type":"26",
         "address":"00185F299965B4:8",
         "ise_id":"39285",
         "direction":"SENDER",
         "parent_device":"39232",
         "index":"8",
         "group_partner":"",
         "aes_available":"false",
         "transmission_mode":"AES",
         "visible":"true",
         "ready_config":"true",
         "operate":"true"
      },
*/

function HmIP_SWO_PR($component) {

    global $export;
    $obj = $export;
    $key = array_search(substr($component['address'], 0, -1)."0", array_column($obj['channels'], 'address'));
    foreach($obj['channels'][$key]['datapoints'] as $datapoint)
    { $status_component[$datapoint['type']] = $datapoint['ise_id']; }
       
    if ($component['parent_device_interface'] == 'HmIP-RF' && $component['visible'] == 'true' && isset($component['ACTUAL_TEMPERATURE'])) {     
        if (!isset($component['color'])) $component['color'] = '#00CC33';
        return '<div class="hh" style=\'border-left-color: '.$component['color'].'; border-left-style: solid; height:65px;\'>'
                 . '<div class="pull-left"><img src="icon/' . $component["icon"] . '" class="icon">' . $component['name'] . '</div>'
                 . '<div class="pull-right">'
                   . '<span class="info" data-id="' . $status_component['LOW_BAT'] . '" data-component="' . $component['component'] . '" data-datapoint="LOW_BAT"></span>'
                   . '<span class="info" data-id="' . $component['ACTUAL_TEMPERATURE'] . '" data-component="' . $component['component'] . '" data-datapoint="ACTUAL_TEMPERATURE"></span>'
                   . '<span class="info" data-id="' . $component['HUMIDITY'] . '" data-component="' . $component['component'] . '" data-datapoint="HUMIDITY"></span>'
                   . '<span class="info" data-id="' . $component['RAINING'] . '" data-component="' . $component['component'] . '" data-datapoint="RAINING"></span>'
                   . '<span class="info" data-id="' . $component['ILLUMINATION'] . '" data-component="' . $component['component'] . '" data-datapoint="ILLUMINATION"></span>'
				   .'<br>'
				  // . '<span class="info" data-id="' . $component['SUNSHINEDURATION'] . '" data-component="' . $component['component'] . '" data-datapoint="SUNSHINEDURATION"></span>'
                 . '</div>'
                 . '<div class="pull-right">'  

                   //. '<span class="info" data-id="' . $component['RAIN_COUNTER'] . '" data-component="' . $component['component'] . '" data-datapoint="RAIN_COUNTER"></span>'
                   . '<span class="info" data-id="' . $component['WIND_SPEED'] . '" data-component="' . $component['component'] . '" data-datapoint="WIND_SPEED"></span>'
                   . '<span class="info" data-id="' . $component['WIND_DIR'] . '" data-component="' . $component['component'] . '" data-datapoint="WIND_DIR"></span>'
                   . '<span class="info" data-id="' . $component['WIND_DIR_RANGE'] . '" data-component="' . $component['component'] . '" data-datapoint="WIND_DIR_RANGE"></span>'
                 . '</div>'
             . '</div>';             
    }
}
