<?php
/*
{
         "component":"HmIP-WRC6",
         "parent_device_type":"HmIP-WRC6",
         "parent_device_interface":"HmIP-RF",
         "name":"Umwelt.Wohnzimmer.Schalter:0",
         "type":"30",
         "address":"000B5709AF3C8D:0",
         "ise_id":"1470",
         "direction":"UNKNOWN",
         "parent_device":"1469",
         "index":"0",
         "group_partner":"",
         "aes_available":"false",
         "transmission_mode":"AES",
         "visible":"true",
         "ready_config":"true",
         "operate":"true",
         "datapoints":[
            {
               "name":"HmIP-RF.000B5709AF3C8D:0.CONFIG_PENDING",
               "type":"CONFIG_PENDING",
               "ise_id":"1471",
               "state":"false",
               "value":"false",
               "valuetype":"2",
               "valueunit":"",
               "timestamp":"1692298798",
               "operations":"5"
            },
            {
               "name":"HmIP-RF.000B5709AF3C8D:0.DUTY_CYCLE",
               "type":"DUTY_CYCLE",
               "ise_id":"1475",
               "state":"false",
               "value":"false",
               "valuetype":"2",
               "valueunit":"",
               "timestamp":"1692298798",
               "operations":"5"
            },
            {
               "name":"HmIP-RF.000B5709AF3C8D:0.LOW_BAT",
               "type":"LOW_BAT",
               "ise_id":"1477",
               "state":"false",
               "value":"false",
               "valuetype":"2",
               "valueunit":"",
               "timestamp":"1692298798",
               "operations":"5"
            },
            {
               "name":"HmIP-RF.000B5709AF3C8D:0.OPERATING_VOLTAGE",
               "type":"OPERATING_VOLTAGE",
               "ise_id":"1481",
               "state":"3.000000",
               "value":"3.000000",
               "valuetype":"4",
               "valueunit":"",
               "timestamp":"1692298798",
               "operations":"5"
            },
            {
               "name":"HmIP-RF.000B5709AF3C8D:0.OPERATING_VOLTAGE_STATUS",
               "type":"OPERATING_VOLTAGE_STATUS",
               "ise_id":"1482",
               "state":"0",
               "value":"0",
               "valuetype":"16",
               "valueunit":"",
               "timestamp":"1692298798",
               "operations":"5"
            },
            {
               "name":"HmIP-RF.000B5709AF3C8D:0.RSSI_DEVICE",
               "type":"RSSI_DEVICE",
               "ise_id":"1483",
               "state":"-48",
               "value":"-48",
               "valuetype":"16",
               "valueunit":"",
               "timestamp":"1692298798",
               "operations":"5"
            },
            {
               "name":"HmIP-RF.000B5709AF3C8D:0.RSSI_PEER",
               "type":"RSSI_PEER",
               "ise_id":"1484",
               "state":"0",
               "value":"0",
               "valuetype":"16",
               "valueunit":"",
               "timestamp":"0",
               "operations":"5"
            },
            {
               "name":"HmIP-RF.000B5709AF3C8D:0.UNREACH",
               "type":"UNREACH",
               "ise_id":"1485",
               "state":"false",
               "value":"false",
               "valuetype":"2",
               "valueunit":"",
               "timestamp":"1692298798",
               "operations":"5"
            },
            {
               "name":"HmIP-RF.000B5709AF3C8D:0.UPDATE_PENDING",
               "type":"UPDATE_PENDING",
               "ise_id":"1489",
               "state":"false",
               "value":"false",
               "valuetype":"2",
               "valueunit":"",
               "timestamp":"1692298798",
               "operations":"5"
            }
         ]
      },
      {
         "component":"HmIP-WRC6",
         "parent_device_type":"HmIP-WRC6",
         "parent_device_interface":"HmIP-RF",
         "name":"HmIP-WRC6 000B5709AF3C8D:1",
         "type":"17",
         "address":"000B5709AF3C8D:1",
         "ise_id":"1493",
         "direction":"SENDER",
         "parent_device":"1469",
         "index":"1",
         "group_partner":"",
         "aes_available":"false",
         "transmission_mode":"AES",
         "visible":"true",
         "ready_config":"true",
         "operate":"true",
         "datapoints":[
            {
               "name":"HmIP-RF.000B5709AF3C8D:1.PRESS_LONG",
               "type":"PRESS_LONG",
               "ise_id":"1494",
               "state":"false",
               "value":"",
               "valuetype":"2",
               "valueunit":"",
               "timestamp":"0",
               "operations":"4"
            },
            {
               "name":"HmIP-RF.000B5709AF3C8D:1.PRESS_SHORT",
               "type":"PRESS_SHORT",
               "ise_id":"1495",
               "state":"false",
               "value":"",
               "valuetype":"2",
               "valueunit":"",
               "timestamp":"0",
               "operations":"4"
            },
            {
               "name":"HmIP-RF.000B5709AF3C8D:1.PRESS_LONG_RELEASE",
               "type":"PRESS_LONG_RELEASE",
               "ise_id":"49432",
               "state":"false",
               "value":"",
               "valuetype":"2",
               "valueunit":"",
               "timestamp":"0",
               "operations":"4"
            },
            {
               "name":"HmIP-RF.000B5709AF3C8D:1.PRESS_LONG_START",
               "type":"PRESS_LONG_START",
               "ise_id":"49433",
               "state":"false",
               "value":"",
               "valuetype":"2",
               "valueunit":"",
               "timestamp":"0",
               "operations":"4"
            }
         ]
      },
      {
         "component":"HmIP-WRC6",
         "parent_device_type":"HmIP-WRC6",
         "parent_device_interface":"HmIP-RF",
         "name":"HmIP-WRC6 000B5709AF3C8D:2",
         "type":"17",
         "address":"000B5709AF3C8D:2",
         "ise_id":"1496",
         "direction":"SENDER",
         "parent_device":"1469",
         "index":"2",
         "group_partner":"",
         "aes_available":"false",
         "transmission_mode":"AES",
         "visible":"true",
         "ready_config":"true",
         "operate":"true",
         "datapoints":[
            {
               "name":"HmIP-RF.000B5709AF3C8D:2.PRESS_LONG",
               "type":"PRESS_LONG",
               "ise_id":"1497",
               "state":"false",
               "value":"",
               "valuetype":"2",
               "valueunit":"",
               "timestamp":"0",
               "operations":"4"
            },
            {
               "name":"HmIP-RF.000B5709AF3C8D:2.PRESS_SHORT",
               "type":"PRESS_SHORT",
               "ise_id":"1498",
               "state":"false",
               "value":"",
               "valuetype":"2",
               "valueunit":"",
               "timestamp":"0",
               "operations":"4"
            },
            {
               "name":"HmIP-RF.000B5709AF3C8D:2.PRESS_LONG_RELEASE",
               "type":"PRESS_LONG_RELEASE",
               "ise_id":"49434",
               "state":"false",
               "value":"",
               "valuetype":"2",
               "valueunit":"",
               "timestamp":"0",
               "operations":"4"
            },
            {
               "name":"HmIP-RF.000B5709AF3C8D:2.PRESS_LONG_START",
               "type":"PRESS_LONG_START",
               "ise_id":"49435",
               "state":"false",
               "value":"",
               "valuetype":"2",
               "valueunit":"",
               "timestamp":"0",
               "operations":"4"
            }
         ]
      },
      {
         "component":"HmIP-WRC6",
         "parent_device_type":"HmIP-WRC6",
         "parent_device_interface":"HmIP-RF",
         "name":"HmIP-WRC6 000B5709AF3C8D:3",
         "type":"17",
         "address":"000B5709AF3C8D:3",
         "ise_id":"1499",
         "direction":"SENDER",
         "parent_device":"1469",
         "index":"3",
         "group_partner":"",
         "aes_available":"false",
         "transmission_mode":"AES",
         "visible":"true",
         "ready_config":"true",
         "operate":"true",
         "datapoints":[
            {
               "name":"HmIP-RF.000B5709AF3C8D:3.PRESS_LONG",
               "type":"PRESS_LONG",
               "ise_id":"1500",
               "state":"false",
               "value":"",
               "valuetype":"2",
               "valueunit":"",
               "timestamp":"0",
               "operations":"4"
            },
            {
               "name":"HmIP-RF.000B5709AF3C8D:3.PRESS_SHORT",
               "type":"PRESS_SHORT",
               "ise_id":"1501",
               "state":"false",
               "value":"",
               "valuetype":"2",
               "valueunit":"",
               "timestamp":"0",
               "operations":"4"
            },
            {
               "name":"HmIP-RF.000B5709AF3C8D:3.PRESS_LONG_RELEASE",
               "type":"PRESS_LONG_RELEASE",
               "ise_id":"49436",
               "state":"false",
               "value":"",
               "valuetype":"2",
               "valueunit":"",
               "timestamp":"0",
               "operations":"4"
            },
            {
               "name":"HmIP-RF.000B5709AF3C8D:3.PRESS_LONG_START",
               "type":"PRESS_LONG_START",
               "ise_id":"49437",
               "state":"false",
               "value":"",
               "valuetype":"2",
               "valueunit":"",
               "timestamp":"0",
               "operations":"4"
            }
         ]
      },
      {
         "component":"HmIP-WRC6",
         "parent_device_type":"HmIP-WRC6",
         "parent_device_interface":"HmIP-RF",
         "name":"HmIP-WRC6 000B5709AF3C8D:4",
         "type":"17",
         "address":"000B5709AF3C8D:4",
         "ise_id":"1502",
         "direction":"SENDER",
         "parent_device":"1469",
         "index":"4",
         "group_partner":"",
         "aes_available":"false",
         "transmission_mode":"AES",
         "visible":"true",
         "ready_config":"true",
         "operate":"true",
         "datapoints":[
            {
               "name":"HmIP-RF.000B5709AF3C8D:4.PRESS_LONG",
               "type":"PRESS_LONG",
               "ise_id":"1503",
               "state":"false",
               "value":"",
               "valuetype":"2",
               "valueunit":"",
               "timestamp":"0",
               "operations":"4"
            },
            {
               "name":"HmIP-RF.000B5709AF3C8D:4.PRESS_SHORT",
               "type":"PRESS_SHORT",
               "ise_id":"1504",
               "state":"false",
               "value":"",
               "valuetype":"2",
               "valueunit":"",
               "timestamp":"0",
               "operations":"4"
            },
            {
               "name":"HmIP-RF.000B5709AF3C8D:4.PRESS_LONG_RELEASE",
               "type":"PRESS_LONG_RELEASE",
               "ise_id":"49438",
               "state":"false",
               "value":"",
               "valuetype":"2",
               "valueunit":"",
               "timestamp":"0",
               "operations":"4"
            },
            {
               "name":"HmIP-RF.000B5709AF3C8D:4.PRESS_LONG_START",
               "type":"PRESS_LONG_START",
               "ise_id":"49439",
               "state":"false",
               "value":"",
               "valuetype":"2",
               "valueunit":"",
               "timestamp":"0",
               "operations":"4"
            }
         ]
      },
      {
         "component":"HmIP-WRC6",
         "parent_device_type":"HmIP-WRC6",
         "parent_device_interface":"HmIP-RF",
         "name":"HmIP-WRC6 000B5709AF3C8D:5",
         "type":"17",
         "address":"000B5709AF3C8D:5",
         "ise_id":"1505",
         "direction":"SENDER",
         "parent_device":"1469",
         "index":"5",
         "group_partner":"",
         "aes_available":"false",
         "transmission_mode":"AES",
         "visible":"true",
         "ready_config":"true",
         "operate":"true",
         "datapoints":[
            {
               "name":"HmIP-RF.000B5709AF3C8D:5.PRESS_LONG",
               "type":"PRESS_LONG",
               "ise_id":"1506",
               "state":"false",
               "value":"",
               "valuetype":"2",
               "valueunit":"",
               "timestamp":"0",
               "operations":"4"
            },
            {
               "name":"HmIP-RF.000B5709AF3C8D:5.PRESS_SHORT",
               "type":"PRESS_SHORT",
               "ise_id":"1507",
               "state":"false",
               "value":"",
               "valuetype":"2",
               "valueunit":"",
               "timestamp":"0",
               "operations":"4"
            },
            {
               "name":"HmIP-RF.000B5709AF3C8D:5.PRESS_LONG_RELEASE",
               "type":"PRESS_LONG_RELEASE",
               "ise_id":"49440",
               "state":"false",
               "value":"",
               "valuetype":"2",
               "valueunit":"",
               "timestamp":"0",
               "operations":"4"
            },
            {
               "name":"HmIP-RF.000B5709AF3C8D:5.PRESS_LONG_START",
               "type":"PRESS_LONG_START",
               "ise_id":"49441",
               "state":"false",
               "value":"",
               "valuetype":"2",
               "valueunit":"",
               "timestamp":"0",
               "operations":"4"
            }
         ]
      },
      {
         "component":"HmIP-WRC6",
         "parent_device_type":"HmIP-WRC6",
         "parent_device_interface":"HmIP-RF",
         "name":"HmIP-WRC6 000B5709AF3C8D:6",
         "type":"17",
         "address":"000B5709AF3C8D:6",
         "ise_id":"1508",
         "direction":"SENDER",
         "parent_device":"1469",
         "index":"6",
         "group_partner":"",
         "aes_available":"false",
         "transmission_mode":"AES",
         "visible":"true",
         "ready_config":"true",
         "operate":"true",
         "datapoints":[
            {
               "name":"HmIP-RF.000B5709AF3C8D:6.PRESS_LONG",
               "type":"PRESS_LONG",
               "ise_id":"1509",
               "state":"false",
               "value":"",
               "valuetype":"2",
               "valueunit":"",
               "timestamp":"0",
               "operations":"4"
            },
            {
               "name":"HmIP-RF.000B5709AF3C8D:6.PRESS_SHORT",
               "type":"PRESS_SHORT",
               "ise_id":"1510",
               "state":"false",
               "value":"",
               "valuetype":"2",
               "valueunit":"",
               "timestamp":"0",
               "operations":"4"
            },
            {
               "name":"HmIP-RF.000B5709AF3C8D:6.PRESS_LONG_RELEASE",
               "type":"PRESS_LONG_RELEASE",
               "ise_id":"49442",
               "state":"false",
               "value":"",
               "valuetype":"2",
               "valueunit":"",
               "timestamp":"0",
               "operations":"4"
            },
            {
               "name":"HmIP-RF.000B5709AF3C8D:6.PRESS_LONG_START",
               "type":"PRESS_LONG_START",
               "ise_id":"49443",
               "state":"false",
               "value":"",
               "valuetype":"2",
               "valueunit":"",
               "timestamp":"0",
               "operations":"4"
            }
         ]
      },



*/

function HMIP_WRC6($component) {
    if ($component['parent_device_interface'] == 'HmIP-RF' && $component['visible'] == 'true' && isset($component['PRESS_SHORT'])) {
        if (!isset($component['color'])) $component['color'] = '#595959';
            return '<div class="hh" style=\'border-left-color: '.$component['color'].'; border-left-style: solid;\'>'
            . '<div class="pull-left"><img src="icon/' . $component["icon"] . '" class="icon">' . $component['name'] . '</div>'
            . '<div class="pull-right">'
                . '<span class="set btn-text" data-set-id="' . $component['PRESS_SHORT'] . '" data-set-value="1">Kurz</span>'
                . '<span class="set btn-text" data-set-id="' . $component['PRESS_LONG'] . '" data-set-value="1">Lang</span>'
            . '</div>'
            . '<div class="clearfix"></div>'
        . '</div>';
    }
}
